# Generated by Django 3.1.2 on 2020-10-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60)),
                ('cut', models.CharField(max_length=60)),
                ('clarity', models.SlugField(max_length=60)),
                ('caratWeight', models.FloatField(max_length=60)),
            ],
        ),
    ]
